### ISSUE TITLE
UnboundLocalError: local variable 'image' referenced before assignment

### ISSUE THREAD

**Issue by Liampour** [c-yn/ConvIR#16]
Hello,
congratulation for your work!! 
I am trying to run the provided dehazing models from the path `ConvIR/Dehazing/ITS` When I am running the following command ` python main.py --mode test --data_dir input/haze4k --test_model checkpoints/nhr-small.pkl --data Haze4K` the following error appears
```
Namespace(batch_size=4, data='Haze4K', data_dir='input/haze4k', learning_rate=0.0001, mode='test', model_name='ConvIR', model_save_dir='results/ConvIR/Training-Results/', num_epoch=300, num_worker=8, print_freq=100, result_dir='results/ConvIR/images/Haze4K', resume='', save_freq=10, save_image=False, test_model='checkpoints/nhr-small.pkl', valid_freq=10, version='small', weight_decay=0)
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    main(args)
  File "main.py", line 28, in main
    _eval(model, args)
  File "/home/username/ConvIR/Dehazing/ITS/eval.py", line 28, in _eval
    for iter_idx, data in enumerate(dataloader):
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/username/ConvIR/Dehazing/ITS/data/data_load.py", line 85, in __getitem__
    image = F.to_tensor(image)
UnboundLocalError: local variable 'image' referenced before assignment
```
the folder structure is like the one proposed with the only difference being that the folders inside haze4k/test renamed from `GT` and `IN` to `gt` and `haze` respectively due to an error appearance. The image names inside the folder are `1.png` and `1_0.89_1.56.png `respectivelly.
Any suggestions on that?

**Comment by Liampour** [comment]
If I use the `--data haze4k` the following error appears: 
`main.py: error: argument --data: invalid choice: 'haze4k' (choose from 'ITS', 'Haze4K', 'NHR', 'GTA5', 'real_haze')`

I also tried to rename the folder with images from haze4k to Haze4K but appears the error reported of first comment

**Comment by Liampour** [comment]
Ok. Now I met some error with file names but after correcting them the following error appears:
```
Namespace(batch_size=4, data='haze4k', data_dir='input/haze4k', learning_rate=0.0001, mode='test', model_name='ConvIR', model_save_dir='results/ConvIR/Training-Results/', num_epoch=300, num_worker=8, print_freq=100, result_dir='results/ConvIR/images/haze4k', resume='', save_freq=10, save_image=False, test_model='checkpoints/haze4k-small.pkl', valid_freq=10, version='small', weight_decay=0)
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    main(args)
  File "main.py", line 28, in main
    _eval(model, args)
  File "/home/username/ConvIR/Dehazing/ITS/eval.py", line 41, in _eval
    pred = model(input_img)[2]
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/ConvIR/Dehazing/ITS/models/ConvIR.py", line 110, in forward
    z2 = self.SCM2(x_2)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/ConvIR/Dehazing/ITS/models/ConvIR.py", line 45, in forward
    x = self.main(x)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/ConvIR/Dehazing/ITS/models/layers.py", line 26, in forward
    return self.main(x)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 4, 768, 1296] to have 3 channels, but got 4 channels instead
```
Note: the dimensions of imported image are 2565x1516

**Comment by Liampour** [comment]
I found the problem the .png files I used had 4 channels (an additional alpha channel per pixel) when I converted to 3 channel it worked! Thank you for your support

**Comment by Liampour** [comment]
When I changed the command to `python main.py --mode test --data_dir input/NHR--test_model checkpoints/nhr-small.pkl --data NHR`  the error reported on the first comment appeared. I tried to change `--data nhr` but it continues to appear
